import { Exam, Student, SchoolSettings } from './types';

export const initialSchoolSettings: SchoolSettings = {
  namaPemerintah: 'PEMERINTAH PROVINSI DAERAH KHUSUS IBUKOTA JAKARTA',
  namaDinas: 'DINAS PENDIDIKAN DAN KEBUDAYAAN',
  namaSekolah: 'SMA NEGERI 1 TELADAN JAKARTA',
  alamatSekolah: 'Jl. Budi Utomo No. 7, Pasar Baru, Sawah Besar, Jakarta Pusat 10710',
  teleponEmail: 'Telp: (021) 3865001 | Email: info@sman1teladan.sch.id | Website: cbt.sman1teladan.sch.id',
  kepalaSekolah: 'Drs. H. Mulyadi, M.Pd.',
  nipKepalaSekolah: '19720514 199802 1 003',
  tahunAjaran: '2025/2026',
  semester: 'Genap (Semester 2)',
};

export const initialStudents: Student[] = [
  { id: 'std-1', nisn: '0071829101', name: 'Ahmad Fauzi Pratama', class: 'X-MIPA 1' },
  { id: 'std-2', nisn: '0071829102', name: 'Siti Nurhaliza Putri', class: 'X-MIPA 1' },
  { id: 'std-3', nisn: '0071829103', name: 'Budi Santoso', class: 'X-MIPA 1' },
  { id: 'std-4', nisn: '0071829104', name: 'Dewi Lestari Kusuma', class: 'X-MIPA 1' },
  { id: 'std-5', nisn: '0071829105', name: 'Rizky Alamsyah', class: 'X-MIPA 1' },
  { id: 'std-6', nisn: '0071829106', name: 'Nabila Zahra Khairunnisa', class: 'X-MIPA 2' },
  { id: 'std-7', nisn: '0071829107', name: 'Dimas Aditya Nugroho', class: 'X-MIPA 2' },
  { id: 'std-8', nisn: '0071829108', name: 'Putri Rahayu Wulandari', class: 'X-MIPA 2' },
  { id: 'std-9', nisn: '0071829109', name: 'Muhammad Farhan', class: 'X-MIPA 2' },
  { id: 'std-10', nisn: '0071829110', name: 'Zahra Aulia Rachman', class: 'X-MIPA 2' },
];

export const initialExams: Exam[] = [
  {
    id: 'exam-1',
    code: 'MTK101',
    title: 'Penilaian Sumatif Tengah Semester: Matematika Wajib (Aljabar & SPLDV)',
    subject: 'Matematika',
    grade: 'Kelas X',
    token: 'CBT2026',
    durationMinutes: 30,
    isActive: true,
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q1',
        number: 1,
        question: 'Himpunan penyelesaian dari sistem persamaan linear dua variabel: 2x + 3y = 8 dan x - 2y = -3 adalah...',
        options: {
          a: 'x = 1, y = 2',
          b: 'x = 2, y = 1',
          c: 'x = -1, y = 3',
          d: 'x = 3, y = -1',
        },
        correctAnswer: 'a',
        explanation: 'Dari x - 2y = -3 diperoleh x = 2y - 3. Substitusi ke 2(2y - 3) + 3y = 8 -> 4y - 6 + 3y = 8 -> 7y = 14 -> y = 2. Maka x = 2(2) - 3 = 1. Jadi (x, y) = (1, 2).',
        category: 'Sistem Persamaan Linear',
      },
      {
        id: 'q2',
        number: 2,
        question: 'Nilai x yang memenuhi pertidaksamaan linear |2x - 5| < 7 adalah...',
        options: {
          a: 'x < -1 atau x > 6',
          b: '-1 < x < 6',
          c: '-6 < x < 1',
          d: 'x > -1',
        },
        correctAnswer: 'b',
        explanation: '|2x - 5| < 7 ekivalen dengan -7 < 2x - 5 < 7. Tambahkan 5 ke ketiga ruas: -2 < 2x < 12. Bagi 2: -1 < x < 6.',
        category: 'Nilai Mutlak',
      },
      {
        id: 'q3',
        number: 3,
        question: 'Diketahui fungsi f(x) = 3x - 4 dan g(x) = x² + 2. Rumus komposisi fungsi (g ∘ f)(x) adalah...',
        options: {
          a: '9x² - 24x + 18',
          b: '9x² - 24x + 14',
          c: '3x² + 2',
          d: '9x² + 16',
        },
        correctAnswer: 'a',
        explanation: '(g ∘ f)(x) = g(f(x)) = (3x - 4)² + 2 = (9x² - 24x + 16) + 2 = 9x² - 24x + 18.',
        category: 'Fungsi Komposisi',
      },
      {
        id: 'q4',
        number: 4,
        question: 'Akar-akar persamaan kuadrat x² - 5x + 6 = 0 adalah x₁ dan x₂. Nilai dari (x₁² + x₂²) adalah...',
        options: {
          a: '11',
          b: '13',
          c: '19',
          d: '25',
        },
        correctAnswer: 'b',
        explanation: 'x₁ + x₂ = 5 dan x₁ · x₂ = 6. Maka x₁² + x₂² = (x₁ + x₂)² - 2(x₁ · x₂) = 5² - 2(6) = 25 - 12 = 13.',
        category: 'Persamaan Kuadrat',
      },
      {
        id: 'q5',
        number: 5,
        question: 'Suku ke-10 dari barisan aritmetika 3, 7, 11, 15, ... adalah...',
        options: {
          a: '37',
          b: '39',
          c: '41',
          d: '43',
        },
        correctAnswer: 'b',
        explanation: 'Suku pertama a = 3, beda b = 4. Suku ke-n: Un = a + (n - 1)b. U10 = 3 + (10 - 1) · 4 = 3 + 36 = 39.',
        category: 'Barisan dan Deret',
      },
    ],
  },
  {
    id: 'exam-2',
    code: 'IPA202',
    title: 'Ujian Harian IPA Terpadu: Ekosistem & Hukum Newton',
    subject: 'Ilmu Pengetahuan Alam',
    grade: 'Kelas X',
    token: 'IPA2026',
    durationMinutes: 25,
    isActive: true,
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q201',
        number: 1,
        question: 'Sebuah balok bermassa 5 kg ditarik dengan gaya tetap 20 N pada lantai licin tanpa gesekan. Percepatan balok tersebut adalah...',
        options: {
          a: '2 m/s²',
          b: '4 m/s²',
          c: '5 m/s²',
          d: '100 m/s²',
        },
        correctAnswer: 'b',
        explanation: 'Berdasarkan Hukum II Newton: a = F / m = 20 N / 5 kg = 4 m/s².',
        category: 'Dinamika Gerak',
      },
      {
        id: 'q202',
        number: 2,
        question: 'Interaksi antara tanaman anggrek yang menempel pada batang pohon mangga tanpa merugikan maupun menguntungkan pohon mangga merupakan contoh simbiosis...',
        options: {
          a: 'Mutualisme',
          b: 'Parasitisme',
          c: 'Komensalisme',
          d: 'Netralisme',
        },
        correctAnswer: 'c',
        explanation: 'Simbiosis komensalisme adalah hubungan di mana satu pihak diuntungkan (anggrek mendapat tempat hidup/cahaya) sedangkan pihak lain tidak dirugikan dan tidak diuntungkan.',
        category: 'Ekosistem & Biologi',
      },
      {
        id: 'q203',
        number: 3,
        question: 'Organel sel yang berfungsi sebagai tempat respirasi sel dan penghasil energi utama (ATP) adalah...',
        options: {
          a: 'Ribosom',
          b: 'Mitokondria',
          c: 'Badan Golgi',
          d: 'Lisosom',
        },
        correctAnswer: 'b',
        explanation: 'Mitokondria sering disebut "the powerhouse of the cell" karena menjadi tempat utama respirasi aerob penghasil ATP.',
        category: 'Struktur Sel',
      },
    ],
  },
];
