import { Exam, Student, SchoolSettings, SavedQuestionPackage, ExamType, QuestionType } from './types';

export const SUBJECT_OPTIONS: string[] = [
  'Pendidikan Pancasila',
  'IPAS (Ilmu Pengetahuan Alam dan Sosial)',
  'Bahasa Jawa',
  'Seni Budaya',
  'Kokurikuler (Proyek P5)',
  'Matematika',
  'Bahasa Indonesia',
  'Bahasa Inggris',
  'Informatika',
  'Ilmu Pengetahuan Alam (IPA)',
  'Ilmu Pengetahuan Sosial (IPS)',
  'Pendidikan Agama & Budi Pekerti',
  'PJOK (Penjasorkes)',
];

export const EXAM_TYPE_OPTIONS: ExamType[] = [
  'Penilaian Akhir Bab',
  'Penilaian Tengah Semester',
  'Asesmen Akhir Semester',
  'Ulangan Harian',
];

export const QUESTION_TYPE_OPTIONS: { id: QuestionType; label: string; description: string }[] = [
  { id: 'pilihan_ganda', label: 'Pilihan Ganda (PG)', description: 'Satu jawaban benar dengan 4 pilihan (A, B, C, D)' },
  { id: 'pilihan_ganda_kompleks', label: 'Pilihan Ganda Kompleks', description: 'Memilih lebih dari satu pernyataan / opsi benar' },
  { id: 'benar_salah', label: 'Benar / Salah', description: 'Menentukan kebenaran pernyataan (Benar / Salah)' },
  { id: 'isian_singkat', label: 'Isian Singkat', description: 'Jawaban berupa kata, angka, atau frasa singkat' },
  { id: 'uraian', label: 'Uraian / Essay', description: 'Jawaban terbuka deskriptif dengan rubrik pembahasan' },
];

export const EDUCATIONAL_IMAGE_PRESETS = [
  {
    name: 'Garuda Pancasila',
    category: 'Pendidikan Pancasila',
    url: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=800&auto=format&fit=crop&q=60',
  },
  {
    name: 'Peta Kepulauan Nusantara Indonesia',
    category: 'IPAS / Geografi',
    url: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&auto=format&fit=crop&q=60',
  },
  {
    name: 'Ekosistem Hutan Tropis & Aliran Energi',
    category: 'IPAS / Sains',
    url: 'https://images.unsplash.com/photo-1511497584788-87676104235f?w=800&auto=format&fit=crop&q=60',
  },
  {
    name: 'Wayang Kulit & Seni Tradisi Jawa',
    category: 'Bahasa Jawa / Seni Budaya',
    url: 'https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=800&auto=format&fit=crop&q=60',
  },
  {
    name: 'Motif Seni Kain Tradisional Nusantara',
    category: 'Seni Budaya',
    url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=60',
  },
  {
    name: 'Pengolahan Sampah & Gaya Hidup Berkelanjutan',
    category: 'Kokurikuler P5',
    url: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop&q=60',
  },
  {
    name: 'Grafik Fungsi Matematika Cartesius',
    category: 'Matematika',
    url: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=60',
  },
];

export const initialSchoolSettings: SchoolSettings = {
  namaPemerintah: 'PEMERINTAH PROVINSI DAERAH KHUSUS IBUKOTA JAKARTA',
  namaDinas: 'DINAS PENDIDIKAN DAN KEBUDAYAAN',
  namaSekolah: 'SMA NEGERI 1 TELADAN JAKARTA',
  alamatSekolah: 'Jl. Budi Utomo No. 7, Pasar Baru, Sawah Besar, Jakarta Pusat 10710',
  teleponEmail: 'Telp: (021) 3865001 | Email: info@sman1teladan.sch.id | Website: cbt.sman1teladan.sch.id',
  kepalaSekolah: 'Drs. H. Mulyadi, M.Pd.',
  nipKepalaSekolah: '19720514 199802 1 003',
  tahunAjaran: '2025/2026',
  semester: 'Genap (Semester 2)',
};

export const initialStudents: Student[] = [
  { id: 'std-1', nisn: '0071829101', name: 'Ahmad Fauzi Pratama', class: 'X-MIPA 1' },
  { id: 'std-2', nisn: '0071829102', name: 'Siti Nurhaliza Putri', class: 'X-MIPA 1' },
  { id: 'std-3', nisn: '0071829103', name: 'Budi Santoso', class: 'X-MIPA 1' },
  { id: 'std-4', nisn: '0071829104', name: 'Dewi Lestari Kusuma', class: 'X-MIPA 1' },
  { id: 'std-5', nisn: '0071829105', name: 'Rizky Alamsyah', class: 'X-MIPA 1' },
  { id: 'std-6', nisn: '0071829106', name: 'Nabila Zahra Khairunnisa', class: 'X-MIPA 2' },
  { id: 'std-7', nisn: '0071829107', name: 'Dimas Aditya Nugroho', class: 'X-MIPA 2' },
  { id: 'std-8', nisn: '0071829108', name: 'Putri Rahayu Wulandari', class: 'X-MIPA 2' },
  { id: 'std-9', nisn: '0071829109', name: 'Muhammad Farhan', class: 'X-MIPA 2' },
  { id: 'std-10', nisn: '0071829110', name: 'Zahra Aulia Rachman', class: 'X-MIPA 2' },
];

export const initialExams: Exam[] = [
  {
    id: 'exam-1',
    code: 'MTK101',
    title: 'Penilaian Sumatif Tengah Semester: Matematika Wajib (Aljabar & SPLDV)',
    subject: 'Matematika',
    grade: 'Kelas X',
    token: 'CBT2026',
    durationMinutes: 30,
    isActive: true,
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q1',
        number: 1,
        question: 'Himpunan penyelesaian dari sistem persamaan linear dua variabel: 2x + 3y = 8 dan x - 2y = -3 adalah...',
        options: {
          a: 'x = 1, y = 2',
          b: 'x = 2, y = 1',
          c: 'x = -1, y = 3',
          d: 'x = 3, y = -1',
        },
        correctAnswer: 'a',
        explanation: 'Dari x - 2y = -3 diperoleh x = 2y - 3. Substitusi ke 2(2y - 3) + 3y = 8 -> 4y - 6 + 3y = 8 -> 7y = 14 -> y = 2. Maka x = 2(2) - 3 = 1. Jadi (x, y) = (1, 2).',
        category: 'Sistem Persamaan Linear',
      },
      {
        id: 'q2',
        number: 2,
        question: 'Nilai x yang memenuhi pertidaksamaan linear |2x - 5| < 7 adalah...',
        options: {
          a: 'x < -1 atau x > 6',
          b: '-1 < x < 6',
          c: '-6 < x < 1',
          d: 'x > -1',
        },
        correctAnswer: 'b',
        explanation: '|2x - 5| < 7 ekivalen dengan -7 < 2x - 5 < 7. Tambahkan 5 ke ketiga ruas: -2 < 2x < 12. Bagi 2: -1 < x < 6.',
        category: 'Nilai Mutlak',
      },
      {
        id: 'q3',
        number: 3,
        question: 'Diketahui fungsi f(x) = 3x - 4 dan g(x) = x² + 2. Rumus komposisi fungsi (g ∘ f)(x) adalah...',
        options: {
          a: '9x² - 24x + 18',
          b: '9x² - 24x + 14',
          c: '3x² + 2',
          d: '9x² + 16',
        },
        correctAnswer: 'a',
        explanation: '(g ∘ f)(x) = g(f(x)) = (3x - 4)² + 2 = (9x² - 24x + 16) + 2 = 9x² - 24x + 18.',
        category: 'Fungsi Komposisi',
      },
      {
        id: 'q4',
        number: 4,
        question: 'Akar-akar persamaan kuadrat x² - 5x + 6 = 0 adalah x₁ dan x₂. Nilai dari (x₁² + x₂²) adalah...',
        options: {
          a: '11',
          b: '13',
          c: '19',
          d: '25',
        },
        correctAnswer: 'b',
        explanation: 'x₁ + x₂ = 5 dan x₁ · x₂ = 6. Maka x₁² + x₂² = (x₁ + x₂)² - 2(x₁ · x₂) = 5² - 2(6) = 25 - 12 = 13.',
        category: 'Persamaan Kuadrat',
      },
      {
        id: 'q5',
        number: 5,
        question: 'Suku ke-10 dari barisan aritmetika 3, 7, 11, 15, ... adalah...',
        options: {
          a: '37',
          b: '39',
          c: '41',
          d: '43',
        },
        correctAnswer: 'b',
        explanation: 'Suku pertama a = 3, beda b = 4. Suku ke-n: Un = a + (n - 1)b. U10 = 3 + (10 - 1) · 4 = 3 + 36 = 39.',
        category: 'Barisan dan Deret',
      },
    ],
  },
  {
    id: 'exam-2',
    code: 'IPA202',
    title: 'Ujian Harian IPA Terpadu: Ekosistem & Hukum Newton',
    subject: 'Ilmu Pengetahuan Alam',
    grade: 'Kelas X',
    token: 'IPA2026',
    durationMinutes: 25,
    isActive: true,
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q201',
        number: 1,
        question: 'Sebuah balok bermassa 5 kg ditarik dengan gaya tetap 20 N pada lantai licin tanpa gesekan. Percepatan balok tersebut adalah...',
        options: {
          a: '2 m/s²',
          b: '4 m/s²',
          c: '5 m/s²',
          d: '100 m/s²',
        },
        correctAnswer: 'b',
        explanation: 'Berdasarkan Hukum II Newton: a = F / m = 20 N / 5 kg = 4 m/s².',
        category: 'Dinamika Gerak',
      },
      {
        id: 'q202',
        number: 2,
        question: 'Interaksi antara tanaman anggrek yang menempel pada batang pohon mangga tanpa merugikan maupun menguntungkan pohon mangga merupakan contoh simbiosis...',
        options: {
          a: 'Mutualisme',
          b: 'Parasitisme',
          c: 'Komensalisme',
          d: 'Netralisme',
        },
        correctAnswer: 'c',
        explanation: 'Simbiosis komensalisme adalah hubungan di mana satu pihak diuntungkan (anggrek mendapat tempat hidup/cahaya) sedangkan pihak lain tidak dirugikan dan tidak diuntungkan.',
        category: 'Ekosistem & Biologi',
      },
      {
        id: 'q203',
        number: 3,
        question: 'Organel sel yang berfungsi sebagai tempat respirasi sel dan penghasil energi utama (ATP) adalah...',
        options: {
          a: 'Ribosom',
          b: 'Mitokondria',
          c: 'Badan Golgi',
          d: 'Lisosom',
        },
        correctAnswer: 'b',
        explanation: 'Mitokondria sering disebut "the powerhouse of the cell" karena menjadi tempat utama respirasi aerob penghasil ATP.',
        category: 'Struktur Sel',
      },
    ],
  },
];

export const initialSavedPackages: SavedQuestionPackage[] = [
  {
    id: 'pkg-pancasila-1',
    title: 'Asesmen Akhir Semester: Pendidikan Pancasila & Kewarganegaraan (Falsafah Negara & UUD 1945)',
    subject: 'Pendidikan Pancasila',
    grade: 'Kelas X SMA/SMK',
    examType: 'Asesmen Akhir Semester',
    topic: 'Falsafah Lambang Negara Garuda Pancasila, Norma Hukum, dan UUD NRI 1945',
    difficulty: 'Sedang / HOTS',
    questionCount: 4,
    questionType: 'pilihan_ganda',
    savedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    isDeployed: false,
    questions: [
      {
        id: 'pkg-q-pan-1',
        number: 1,
        question: 'Perhatikan lambang negara Garuda Pancasila pada gambar di bawah ini.\n\nSemboyan "Bhinneka Tunggal Ika" yang dicengkeram oleh kedua kaki burung Garuda melambangkan...',
        imageUrl: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=800&auto=format&fit=crop&q=60',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Kekuatan pertahanan militer Indonesia yang tak tertandingi',
          b: 'Kesatuan dalam keberagaman suku, agama, ras, dan antargolongan bangsa Indonesia',
          c: 'Kedaulatan ekonomi rakyat yang berdiri di atas kaki sendiri',
          d: 'Kebanggaan bangsa atas kekayaan rempah-rempah masa lampau',
        },
        correctAnswer: 'b',
        explanation: 'Semboyan Bhinneka Tunggal Ika bermakna berbeda-beda tetapi tetap satu jua, menegaskan persatuan kebangsaan di tengah pluralitas bangsa.',
        category: 'Simbol Negara',
      },
      {
        id: 'pkg-q-pan-2',
        number: 2,
        question: 'Penerapan nilai sila ke-2 Pancasila "Kemanusiaan yang Adil dan Beradab" dalam kehidupan sekolah diwujudkan dengan tindakan...',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Memilih teman kelompok belajar hanya yang memiliki kesamaan daerah asal',
          b: 'Menghargai harkat dan martabat setiap teman tanpa diskriminasi atau perundungan (bullying)',
          c: 'Menolak bermusyawarah ketika keputusan kelompok berbeda pendapat',
          d: 'Mengutamakan kepentingan pribadi di atas tugas piket kelas bersama',
        },
        correctAnswer: 'b',
        explanation: 'Sila ke-2 menekankan persamaan derajat, hak, dan kewajiban asasi setiap manusia tanpa membeda-bedakan suku, keturunan, agama, dan gender.',
        category: 'Nilai-Nilai Pancasila',
      },
      {
        id: 'pkg-q-pan-3',
        number: 3,
        question: 'Pernyataan berikut merupakan wujud implementasi musyawarah mufakat (Sila ke-4 Pancasila). Tentukan kebenaran pernyataan: "Keputusan musyawarah harus dipertanggungjawabkan secara moral kepada Tuhan Yang Maha Esa serta menjunjung tinggi martabat manusia."',
        questionType: 'benar_salah',
        options: {
          a: 'Benar',
          b: 'Salah',
          c: '-',
          d: '-',
        },
        correctAnswer: 'a',
        explanation: 'Benar. Sikap demokratis berlandaskan Pancasila menempatkan tanggung jawab moral kepada Tuhan YME dan nilai keadilan.',
        category: 'Demokrasi Pancasila',
      },
      {
        id: 'pkg-q-pan-4',
        number: 4,
        question: 'Manakah di antara prinsip berikut yang sesuai dengan Pasal 27 Ayat (3) UUD NRI 1945 mengenai hak dan kewajiban warga negara?',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Setiap warga negara berhak dan wajib ikut serta dalam upaya pembelaan negara',
          b: 'Hanya aparat TNI dan POLRI yang memiliki kewajiban menjaga pertahanan negara',
          c: 'Bela negara hanya wajib bagi warga yang berusia di atas 25 tahun',
          d: 'Upaya pembelaan negara dilakukan secara sukarela tanpa payung undang-undang',
        },
        correctAnswer: 'a',
        explanation: 'Pasal 27 ayat 3 UUD NRI 1945 menyatakan tegas bahwa setiap warga negara berhak dan wajib ikut serta dalam upaya pembelaan negara.',
        category: 'Konstitusi & Hak Warga Negara',
      },
    ],
  },
  {
    id: 'pkg-ipas-1',
    title: 'Penilaian Akhir Bab: IPAS (Interaksi Makhluk Hidup & Ekosistem Terpadu)',
    subject: 'IPAS (Ilmu Pengetahuan Alam dan Sosial)',
    grade: 'Kelas X / Fase E',
    examType: 'Penilaian Akhir Bab',
    topic: 'Aliran Energi Rantai Makanan, Siklus Biogeokimia, dan Pencemaran Lingkungan',
    difficulty: 'Sedang / HOTS',
    questionCount: 3,
    questionType: 'pilihan_ganda',
    savedAt: new Date(Date.now() - 86400000).toISOString(),
    isDeployed: false,
    questions: [
      {
        id: 'pkg-q-ipas-1',
        number: 1,
        question: 'Amatilah ilustrasi ekosistem alami hutan tropis berikut ini.\n\nDalam suatu jaring-jaring makanan ekosistem hutan, jika populasi burung pemakan serangga mengalami penurunan drastis akibat perburuan liar, dampak ekologis yang paling mungkin terjadi secara langsung adalah...',
        imageUrl: 'https://images.unsplash.com/photo-1511497584788-87676104235f?w=800&auto=format&fit=crop&q=60',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Populasi ulat dan belalang hama dedaunan akan melonjak pesat merusak tajuk pohon',
          b: 'Populasi elang pemangsa tingkat puncak akan meningkat tajam',
          c: 'Produktivitas primer tanaman autotrof langsung meningkat drastis',
          d: 'Dekomposer di lantai hutan akan berhenti menguraikan materi organik',
        },
        correctAnswer: 'a',
        explanation: 'Burung pemakan serangga berperan sebagai pengendali populasi herbivora (serangga hama). Pengurangan predator alami memicu ledakan populasi hama.',
        category: 'Dinamika Ekosistem',
      },
      {
        id: 'pkg-q-ipas-2',
        number: 2,
        question: 'Gas rumah kaca yang paling dominan dihasilkan dari pembakaran bahan bakar fosil dan berkontribusi terhadap kenaikan suhu rata-rata global adalah...',
        questionType: 'isian_singkat',
        options: {
          a: 'Karbondioksida (CO2)',
          b: 'Gas Metana (CH4)',
          c: 'Klorofluorokarbon (CFC)',
          d: 'Gas Oksigen (O2)',
        },
        correctAnswer: 'Karbondioksida',
        explanation: 'Karbondioksida (CO2) merupakan gas rumah kaca utama antropogenik hasil pembakaran batu bara, minyak bumi, dan deforestasi.',
        category: 'Pemanasan Global',
      },
      {
        id: 'pkg-q-ipas-3',
        number: 3,
        question: 'Fenomena eutrofikasi di danau atau perairan air tawar dipicu oleh penumpukan limbah pupuk fosfat dan nitrat dari aktivitas pertanian. Dampak fatal fenomena ini terhadap biota air adalah...',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Meningkatnya kadar oksigen terlarut (Dissolved Oxygen) di dasar perairan',
          b: 'Blooming alga menutupi permukaan air yang menyebabkan penurunan oksigen terlarut dan kematian ikan secara massal',
          c: 'Air menjadi jernih karena pertumbuhan pesat tanaman paku air',
          d: 'Penurunan populasi bakteri pengurai anaerobik di sedimen lumpur',
        },
        correctAnswer: 'b',
        explanation: 'Eutrofikasi menyebabkan alga blooming. Saat alga mati, penguraiannya oleh bakteri menyerap hampir seluruh oksigen terlarut sehingga menyebabkan hipoksia fatal bagi ikan.',
        category: 'Pencemaran Lingkungan',
      },
    ],
  },
  {
    id: 'pkg-jawa-1',
    title: 'Penilaian Tengah Semester: Bahasa Jawa (Unggah-Ungguh Basa & Cerita Wayang)',
    subject: 'Bahasa Jawa',
    grade: 'Kelas X / Fase E',
    examType: 'Penilaian Tengah Semester',
    topic: 'Unggah-Ungguh Basa Jawa (Krama Alus), Serat Wulangreh, dan Tokoh Wayang Mahabarata',
    difficulty: 'Sedang / HOTS',
    questionCount: 3,
    questionType: 'pilihan_ganda',
    savedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    isDeployed: false,
    questions: [
      {
        id: 'pkg-q-jawa-1',
        number: 1,
        question: 'Gatosaken gambar wayang ing ngandhap menika!\n\nTokoh wayang Satriya Madukara ingkang gadhah watak satriya, luhur bebudene, remen tetulung, sarta gadhah sanjata jemparing Panah Pasopati inggih menika...',
        imageUrl: 'https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=800&auto=format&fit=crop&q=60',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Raden Werkudara',
          b: 'Raden Janaka (Arjuna)',
          c: 'Prabu Puntadewa',
          d: 'Raden Gatotkaca',
        },
        correctAnswer: 'b',
        explanation: 'Raden Janaka utawi Arjuna minangka satriya panengahing Pandhawa ingkang kasatriyane ing Madukara, kondhang prigel manah mawi Panah Pasopati.',
        category: 'Carita Wayang',
      },
      {
        id: 'pkg-q-jawa-2',
        number: 2,
        question: 'Ukara ing ngandhap menika ingkang trep miturut unggah-ungguh basa Krama Alus nalika matur dhateng Bapak utawi Ibu Guru inggih menika...',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Kula badhe dhahar rumiyin Bu guru, mangga sareng.',
          b: 'Nyuwun pangapunten Pak Guru, buku tugas kula sampun kula aturaken wonten meja kantor panjenengan.',
          c: 'Pak Guru, kula nyuwun pirsa panjenengan wau mangan wonten pundi?',
          d: 'Bapak tindak kantor numpak sepedha motor kula mawon.',
        },
        correctAnswer: 'b',
        explanation: 'Krama Alus kagem ngurmati guru ngginakaken tembung aturaken, panjenengan, sarta dhiri pribadi mboten pareng dipunkramakaken alus (kula aturaken).',
        category: 'Unggah-Ungguh Basa',
      },
      {
        id: 'pkg-q-jawa-3',
        number: 3,
        question: 'Tembung "Mangan" menawi dipunowahi dados Krama Andhap/Lugu kagem piyambak inggih menika "Nedha", wondene kagem tiyang sepuh (Krama Alus) inggih menika...',
        questionType: 'isian_singkat',
        options: {
          a: 'Dhahar',
          b: 'Neda',
          c: 'Sare',
          d: 'Tindak',
        },
        correctAnswer: 'Dhahar',
        explanation: 'Tembung mangan kramane nedha (kagem dhiri pribadi), lan dhahar (kagem tiyang sanes ingkang dipunurmati).',
        category: 'Kamus Basa Jawa',
      },
    ],
  },
  {
    id: 'pkg-seni-1',
    title: 'Penilaian Akhir Bab: Seni Budaya (Ragam Seni Rupa & Musik Tradisi Nusantara)',
    subject: 'Seni Budaya',
    grade: 'Kelas X',
    examType: 'Penilaian Akhir Bab',
    topic: 'Kritik Seni Rupa Terapan, Motif Tradisional Nusantara, dan Alat Musik Gamelan',
    difficulty: 'Sedang / HOTS',
    questionCount: 3,
    questionType: 'pilihan_ganda',
    savedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    isDeployed: false,
    questions: [
      {
        id: 'pkg-q-seni-1',
        number: 1,
        question: 'Perhatikan ragam karya tekstil kriya tradisional Indonesia pada gambar berikut ini.\n\nMotif hias yang menggunakan garis-garis diagonal meliuk berulang menyerupai ombak samudra dan melambangkan semangat yang tak pernah padam serta kesinambungan hidup adalah motif batik...',
        imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=60',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Batik Parang Rusak',
          b: 'Batik Mega Mendung',
          c: 'Batik Kawung',
          d: 'Batik Tambal',
        },
        correctAnswer: 'a',
        explanation: 'Motif Parang berbentuk huruf S meliuk miring berkesinambungan laksana ombak karang, melambangkan keteguhan dan perjuangan luhur.',
        category: 'Seni Rupa Kriya',
      },
      {
        id: 'pkg-q-seni-2',
        number: 2,
        question: 'Alat musik gamelan Jawa yang berbentuk bilah-bilah perunggu yang dipukul dan berfungsi sebagai pembawa melodi pokok (balungan) dalam gending adalah...',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Kendhang',
          b: 'Saron / Demung',
          c: 'Gong Ageng',
          d: 'Rebab',
        },
        correctAnswer: 'b',
        explanation: 'Saron dan demung memainkan nada balungan (rangka melodi utama) dalam struktur gending gamelan.',
        category: 'Seni Musik Tradisi',
      },
      {
        id: 'pkg-q-seni-3',
        number: 3,
        question: 'Dalam apresiasi karya seni rupa, unsur visual yang memberikan kesan kedalaman tiga dimensi (gelap terang) melalui intensitas cahaya yang mengenai objek disebut...',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Tekstur',
          b: 'Value / Gelap Terang',
          c: 'Proporsi',
          d: 'Irama',
        },
        correctAnswer: 'b',
        explanation: 'Value atau gradasi gelap terang menciptakan ilusi ruang, volume, dan plastisitas pada bidang dwimatra (2D).',
        category: 'Apresiasi Seni',
      },
    ],
  },
  {
    id: 'pkg-p5-1',
    title: 'Asesmen Kokurikuler: Proyek Penguatan Profil Pelajar Pancasila (P5)',
    subject: 'Kokurikuler (Proyek P5)',
    grade: 'Fase E (SMA/SMK)',
    examType: 'Asesmen Akhir Semester',
    topic: 'Tema: Gaya Hidup Berkelanjutan (Pengelolaan Sampah, Bank Sampah, & Ekonomi Sirkular)',
    difficulty: 'Sedang / HOTS',
    questionCount: 3,
    questionType: 'pilihan_ganda',
    savedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    isDeployed: false,
    questions: [
      {
        id: 'pkg-q-p5-1',
        number: 1,
        question: 'Perhatikan potret aksi pengelolaan limbah padat pada foto berikut ini.\n\nDalam prinsip 5R (Refuse, Reduce, Reuse, Repurpose, Recycle) pada tema Gaya Hidup Berkelanjutan P5, langkah paling utama dan memiliki dampak reduksi emisi karbon tertinggi adalah...',
        imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop&q=60',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Refuse (Menolak penggunaan kemasan sekali pakai sejak dari hulu)',
          b: 'Recycle (Mendaur ulang botol plastik di pabrik pengolahan)',
          c: 'Incineration (Membakar sampah di insinerator sekolah)',
          d: 'Landfill (Membuang seluruh sampah ke Tempat Pembuangan Akhir)',
        },
        correctAnswer: 'a',
        explanation: 'Hirarki pengelolaan sampah tertinggi adalah pencegahan timbulan sampah (Refuse & Reduce). Menolak kemasan sekali pakai menghentikan sampah sejak hulu.',
        category: 'Gaya Hidup Berkelanjutan',
      },
      {
        id: 'pkg-q-p5-2',
        number: 2,
        question: 'Dimensi Profil Pelajar Pancasila yang paling tercermin ketika siswa berkolaborasi dalam kelompok lintas kelas merancang komposter organik sekolah dengan pembagian tugas yang adil adalah...',
        questionType: 'pilihan_ganda',
        options: {
          a: 'Mandiri dan Bernalar Kritis',
          b: 'Bergotong Royong dan Kreatif',
          c: 'Berkebinekaan Global semata',
          d: 'Individualis Terarah',
        },
        correctAnswer: 'b',
        explanation: 'Bergotong royong (kolaborasi, kepedulian, berbagi) dan Kreatif (menghasilkan gagasan orisinal karya nyata) merupakan inti proyek komposting bersama.',
        category: 'Dimensi Profil Pelajar Pancasila',
      },
      {
        id: 'pkg-q-p5-3',
        number: 3,
        question: 'Cairan hasil fermentasi anaerobik limbah organik basah dapur (seperti kulit buah dan sisa sayuran) yang dicampur dengan molase/gula dan air, serta berkhasiat sebagai pupuk cair alami dan pembersih ramah lingkungan dinamakan...',
        questionType: 'isian_singkat',
        options: {
          a: 'Eco-Enzyme',
          b: 'Bioplastik',
          c: 'Biobriket',
          d: 'Pestisida Kimia',
        },
        correctAnswer: 'Eco-Enzyme',
        explanation: 'Eco-Enzyme adalah larutan multiguna hasil fermentasi limbah organik dapur (sisa buah dan sayuran) bersama gula merah dan air selama 3 bulan.',
        category: 'Produk Karya P5',
      },
    ],
  },
];

